name: T005 GITHUB_ENV Append

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Export Version
        run: echo "PR=${{ github.event.inputs.version }}" >> "$GITHUB_ENV"