name: T010 Python Command

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Python
        run: python -c "print('${{ github.event.issue.title }}')"